---
title: "Assignment 1: Introduction"
author: "Kyle Falk"
output: pdf_document
---

## OVERVIEW

This exercise accompanies the introductory material in Environmental Data Analytics. 

## Directions
1.  Rename this file `<FirstLast>_A01_Introduction.Rmd` (replacing `<FirstLast>` with your first and last name).
2.  Change "Student Name" on line 3 (above) with your name.
3.  Work through the steps, **creating code and output** that fulfill each instruction.
4.  Be sure to **answer the questions** in this assignment document.
5.  When you have completed the assignment, **Knit** the text and code into a single PDF file.
6.  After Knitting, submit the completed exercise (PDF file) to the appropriate assignment section on Canvas.


## 1) Discussion Questions
Enter answers to the questions just below the >Answer: prompt.

1. What are your previous experiences with data analytics, R, and Git? Include both formal and informal training.

> Answer: 
No experience with R aside from looking at and downloading stuff over the summer, as well as briefly using it in a lab in undergrad. I have downloaded files from Git, but never made an account or uploaded my own files.

2. Are there any components of the course about which you feel confident?

> Answer:
I am generally pretty good at working with computers and managing files for different purposes.

3. Are there any components of the course about which you feel apprehensive?

> Answer:
Although the class is structured for a student to succeed with no background with R, I am apprehensive that it might not click for me or that I may fall behind, because I have been out of school for almost three years.

## 2) GitHub

Provide a link below to your forked course repository in GitHub. Make sure you have pulled all recent changes from the course repository and that you have updated your course README file, committed those changes, and pushed them to your GitHub account.

> Answer: 
https://github.com/kfalk100/EDE_Fall2025

## 3) Knitting
When you have completed this document, click the `knit` button.This should produce a PDF copy of your markdown document. Submit this PDF to Canvas 
